/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as avfSol from "./AVF.sol";
export type { avfSol };
export type { DisputeEscrow } from "./DisputeEscrow";
export type { IERC223Recipient } from "./IERC223Recipient";
export type { OutcomeRegistry } from "./OutcomeRegistry";
