version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-production:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@nomicfoundation/*"
          - "hardhat"
          - "@openzeppelin/*"
      npm-development:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
