/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC223Receiver,
  IERC223ReceiverInterface,
} from "../../../contracts/AVF.sol/IERC223Receiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "tokenFallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC223Receiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC223ReceiverInterface {
    return new Interface(_abi) as IERC223ReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC223Receiver {
    return new Contract(address, _abi, runner) as unknown as IERC223Receiver;
  }
}
