/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC223Recipient,
  IERC223RecipientInterface,
} from "../../contracts/IERC223Recipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "tokenReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC223Recipient__factory {
  static readonly abi = _abi;
  static createInterface(): IERC223RecipientInterface {
    return new Interface(_abi) as IERC223RecipientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC223Recipient {
    return new Contract(address, _abi, runner) as unknown as IERC223Recipient;
  }
}
